---
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-sample
spec:
  parallelism: 4 // 4 separate runners to generate more load in parallel
  script:
    configMap:
      name: 'user-profile-test'
      file: 'tests/userProfile.test.js'